services:
  ollama:
    container_name: ollama
    image: ollama/ollama:${OLLAMA_VERSION}
    restart: unless-stopped
    networks:
      - ollama-network
    ports:
      - ${OLLAMA_PORT}:11434
    volumes:
      - ${OLLAMA_VOLUME}:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  webui:
    container_name: webui
    image: ghcr.io/open-webui/open-webui:${WEBUI_VERSION}
    restart: unless-stopped
    networks:
      - ollama-network
    ports:
      - ${WEBUI_PORT}:8080
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
    volumes:
      - ${WEBUI_VOLUME}:/app/backend/data

networks:
  ollama-network:
    name: ollama-network
    external: false
